### ISSUE TITLE
feat(burner) add total supply

### ISSUE THREAD

**Issue by Sen-Com** [deving-zone-community/community-furnace#2]
<img width="559" alt="Bildschirmfoto 2023-07-17 um 10 34 42" src="https://github.com/deving-zone-community/white-whale-furnace/assets/86837735/31bcbf11-d522-4bf8-8755-dcd813bb4df9">

Next to the Total Whale Burned, it should show the total supply.

**Comment by silvermind** [comment]
@Sen-Com total whale burned is the suppy of $ash. Do you mean the Total $whale supply?
